### ISSUE TITLE
Disabling the dashboard results in a malformed deployment definition.

### ISSUE THREAD

**Issue by iamangus** [project-octal/terraform-kubernetes-traefik#5]
https://github.com/project-octal/terraform-kubernetes-traefik/blob/7a13ddce65535e53245f7b5478260266e55f4115/deployments.tf#L74

Disabling the dashboard results in a pair of quotation marks being passed in as an arg. This seems to result in all args proceeding it being ignored.

**Comment by dylanturn** [comment]
+1
I just ran into this too.....

**Comment by dylanturn** [comment]
Turns out `--entryPoints.traefik.address=:9000/tcp` can't be disabled because Traefik uses it as a health check.

Issue is fixed in version `1.1.3`
